# Uncomment to add libraries
# LIBRARIES += ../deps/stlplus/containers
CXXFLAGS += -ggdb -std=c++11 -Wall -Wextra
CXXFLAGS += -I../include -I../include -I./
# Enable to see the state machine transition
# CXXFLAGS += -DTRACE_STATE_MACHINE
LDFLAGS += -Wall
include ../deps/makefiles/gcc.mak
