# Uncomment to add libraries
# LIBRARIES += ../deps/stlplus/containers
CXXFLAGS += -ggdb -std=c++11 -Wall -Wextra
CXXFLAGS += -I./ -I../include -I../deps/plog/include -I../deps/botan2/build/include
# Enable to see the state machine transition
# CXXFLAGS += -DTRACE_STATE_MACHINE
LDFLAGS += -Wall
include ../deps/makefiles/gcc.mak
